CREATE TABLE  IF NOT EXISTS `ESPACECOLLABORATIF` (
  `ID_ESPACECOLLABORATIF` bigint(20) NOT NULL auto_increment,
  `CODE` varchar(128) default '',
  `ACTIF` char(1) default '',
  `THEME` varchar(8) default '',
  `MODIFICATION_LISTE_MEMBRES` char(1) default '',
  `INSCRIPTION_FRONT` char(1) default '',
  `INTITULE` varchar(255) default '',
  `CODE_STRUCTURE` varchar(64) default '',
  `GROUPES_MEMBRES` text,
  `UTILISATEURS_MEMBRES` text,
  `ROLES_MEMBRE` varchar(255) default '',
  `UTILISATEURS_ROLES_RESPONSABLES` text,
  `CODE_PAGE_ACCUEIL` varchar(64) default '',
  `FONDATEUR` varchar(30) default '',
  `COULEUR_TITRE` varchar(30) default '',
  `COULEUR_FOND` varchar(30) default '',
  `DESCRIPTION` text,
  `INSCRIPTIONS_EN_COURS` text,
  `SERVICES` text,
  `DATE_CREATION` date default '1970-01-01',
  `TAILLE_ESPACE` varchar(255) default '',
  `TAILLE_FICHIER` varchar(255) default '',
  `PERIODICITE_NEWSLETTER` char(1) default '',
  `CONTENU_NEWSLETTER` varchar(255) default '',
  `DATE_DERNIER_ENVOI_NEWSLETTER` date default '1970-01-01',
  `DATE_ENVOI_NEWSLETTER` date default '1970-01-01',
  `GROUPES_INSCRIPTION` text,
  `GROUPES_CONSULTATION` text,
  `NOTIFICATION_MAIL` char(1) default '',
  `LISTE_FICHES` text,
  `FIL_ESPACE` char(1) default '',
  `LISTE_STRUCTURES` text,
  `CODE_RUBRIQUE` varchar(255) default '',
  `LANGUE` char(1) default '0',
  `ENTETE_ESPACE` text,
  `PIED_ESPACE` text,
  PRIMARY KEY  (`ID_ESPACECOLLABORATIF`),
  KEY `IDX_CODE` (`CODE`),
  KEY `IDX_CODE_RUBRIQUE` (`CODE_RUBRIQUE`),
  KEY `IDX_CODE_STRUCTURE` (`CODE_STRUCTURE`),
  KEY `IDX_THEME` (`THEME`)
) ENGINE=MyISAM CHARACTER SET utf8 COLLATE utf8_general_ci;
